### ISSUE TITLE
Wrong page break after \section because of \setkomafont

### ISSUE THREAD

**Issue by tingtingben** [derric/cleanthesis#10]
Hi there,
First of all, thank you so much for providing the cleanthesis package!
I've noticed a possible issue about page breaking after a \section command. My document is, say, a lot of text, then \section{}, then \subsection{}, then a lot of text again. However, the page breaks between the section and subsection headings.
I've read here (http://tex.stackexchange.com/questions/14554/heading-at-the-bottom-of-the-page) that it could come from the \setkomafont definition.
Indeed, when I deactivate the definition of the section style (\setkomafont{section}{\thesissectionfont} ; line 521 in the latest commit, 55ab75fe8a), the page breaks normally. But the section heading doesn't look so good anymore ;)
For the moment I'll add a \pagebreak where it is needed, but if you have any idea how to fix that, it will be much appreciated.
Thanks for your help!

**Comment by johannesbottcher** [comment]
I cannot reproduce that with a current TeX Live.

**Comment by guillerodriguez** [comment]
I can reproduce this problem with TeX Live 2016/Debian and either cleanthesis-0.3.1 or current git master.

I am attaching sample tex files to show the problem, as well as the generated pdf:

 * Input files: [my-thesis.zip](https://github.com/derric/cleanthesis/files/1395336/my-thesis.zip)
 * Generated pdf: [my-thesis.pdf](https://github.com/derric/cleanthesis/files/1395333/my-thesis.pdf)

Also here's a screenshot:

![screenshot](https://user-images.githubusercontent.com/2486184/31728756-7015f762-b42d-11e7-9711-74a934c1585e.png)

**Comment by guillerodriguez** [comment]
Posted a question in tex.stackexchange.com:

https://tex.stackexchange.com/questions/396824/page-break-after-section-in-cleanthesis
