### ISSUE TITLE
twoside=false gives a bunch of errors

### ISSUE THREAD

**Issue by Aapjes94** [derric/cleanthesis#102]
`Package Fancyhdr Warning: \fancyfootoffset's 'E' option without twoside option is useless on input line 150.`

`Package Fancyhdr Warning: \fancyfoot's 'E' option without twoside option is useless on input line 150.`

Line 150: `\pagestyle{maincontentstyle}`
 
It gives the same errors with where \chapter{...} of \section{...} is called, but not for every chapter or section.

**Comment by johannesbottcher** [comment]
It is a warning, not an error. And it to be expected for a one-sided
document.
