### ISSUE TITLE
Error when using pdfpages with cleanthesis 0.4.0

### ISSUE THREAD

**Issue by juanlufont** [derric/cleanthesis#107]
It seems the latest updates of the texlive packages in Debian testing (Bullseye) make `cleanthesis` incompatible with `pdfpages`.

Until yesterday (exactly the day I have finished writing my dissertation :-), cleanthesis 0.3.1, default version provided by Debian until then, was working fine with pdfpages v0.5l.

They have just rolled an update of texlive packages in Debian testing, including an update for cleanthesis to version 0.4.0. On the other hand pdfpages remains at v0.5l. After this update, the pdf generation process gets broken for me, when I run `pdflatex my-thesis.tex` I get:
```
! Undefined control sequence.
\in@ #1#2->\begingroup \def \in@@ 
                                  ##1#1{}\toks@ \expandafter {\in@@ #2{}{}#1...
l.10 \section{Postcards: My Address}
```
which looks like being the same problem than this one reported a couple of years ago: https://github.com/derric/cleanthesis/issues/85#issuecomment-297650432
The way `xcolor` is loaded seems to be the root of the problem, as far as I can understand (but I may be wrong).

Reproducing the problem is easy, it only requires to add
```
\usepackage{pdfpages}
```
at the end of the example file `my-thesis-setup.tex` and try to generate a PDF with `pdflatex my-thesis.tex`.

The same setup but using cleanthesis 0.3.1 still works great with pdfpages.

**Comment by derric** [comment]
Thanks @juanlufont! This issue should be with 40d24a1e89501090294d185ecf037182801405d0. It will be included in the next release.
If there are any other issues related to pdfpages, please create a new issue.
