### ISSUE TITLE
Usage of tocloft with KOMA-Script class is not recommended

### ISSUE THREAD

**Issue by israelbuitron** [derric/cleanthesis#108]
There is one warning thrown, even in a minimal example of cleanthesis document:
```tex
/usr/local/texlive/2019/texmf-dist/tex/latex/cleanthesis/cleanthesis.sty: Class scrreprt Warning: Usage of package `tocloft' together(scrreprt)              with a KOMA-Script class is not recommended.
```

In using `cleanthesis` class version `0.4.0`.

It is [documented at Tex Stackoverflow][1] that `tocloft` package is not fully-compatible with `scrreprt`, which is the `documentclass` used in `cleanthesis` examples.

[1]: https://tex.stackexchange.com/questions/73248/what-packages-are-incompatible-with-koma-script#73288

**Comment by derric** [comment]
Thanks @israelbuitron! This should be fixed with a780a5a5c7117591520cf4b2880f946d46787b78. It will be included in the next release.
