### ISSUE TITLE
PDF note generating due to 

### ISSUE THREAD

**Issue by koencolpaert** [derric/cleanthesis#11]
Hi,

I'm new to working with LaTeX so could you please point out to me how to solve this problem. When I load the default template, adapt some lines and try to generate a new pdf I get:

!pdfTeX error: pdflatex (file ec-qhvr): Font ec-qhvr at 540 not found

I found the missing files as a download (ec-qhvr.tfm)but what's the next step? Or is there a line I can comment out and not use this?

**Comment by derric** [comment]
Hey, can you provide some more general information about your configuration (which Tex dist, OS), please.
It seams that some fonts are missing. Please try to install the **tex-gyre**.

**Comment by koencolpaert** [comment]
Thanks for your follow-up Derric.
I'm running MiKTex 2.9 on Win 7 64bit. Don't know what caused it but I solved it by re-installing MiKTex and while compiling the document it grabbed the desired tex-gyre.
