### ISSUE TITLE
B5 format make chapter's footers dissapear

### ISSUE THREAD

**Issue by vicruiser** [derric/cleanthesis#140]
I selected instead of the A4 format, the B5.

 I guess the positions of the footers is manually adjusted. Basically, the title of the Chapter disappears while the title of the section is still there. 

![image](https://github.com/derric/cleanthesis/assets/14994349/4f76fefb-ca6f-4de2-b3ab-53946f392cda)

![image](https://github.com/derric/cleanthesis/assets/14994349/9a427f3e-d79d-400e-a60e-83278b61c85f)

I'm not really sure which number I should adjust. Any kind of help is welcome. Thanks in advance.

**Comment by derric** [comment]
Hey, the positioning of footer elements is handled in https://github.com/derric/cleanthesis/blob/63d1fdd815e3f78fd1cb64c58f8a9a1c28cad57c/cleanthesis.sty#L403 lines 403-428. Guess you'll have to play around with the values until you're satisfied with the result.

Hope this helps, Best.

**Comment by vicruiser** [comment]
Perfect, fixed! thank you so much!
