### ISSUE TITLE
ShareLaTeX template

### ISSUE THREAD

**Issue by dmgawel** [derric/cleanthesis#15]
ShareLaTeX is a free and open, easy to use, online, collaborative LaTeX editor.

I think it could be a good idea to publish cleanthesis as ShareLaTeX template:
https://www.sharelatex.com/templates

**Comment by derric** [comment]
Basically you are right; I think the best thing of platforms like ShareLaTeX is the collaboration aspect. 
But, and please correct me if I am wrong, a thesis document is usually not created and edited collaboratively. So right now I can not see a specific advantage in publishing the style at yet another online location. I think this would also result in a more complicated update process for me.

**Comment by dmgawel** [comment]
Your answer is clear. Thanks for consideration ;-)
