### ISSUE TITLE
CTAN and License

### ISSUE THREAD

**Issue by vermiculus** [derric/cleanthesis#16]
TeX-related materials belong on CTAN for a number of reasons, not the least of which is to distribute the material to TeX users. There are many classes like this one already available on CTAN -- there's no reason this can't join them.

I would also consider re-licensing under the LaTeX Project Public License (LPPL) -- [the GPL is far too restrictive](http://tex.stackexchange.com/a/69010/17423).

**Comment by FinweNoldoran** [comment]
+1

**Comment by derric** [comment]
Hey. So, there are two points here:

1. CTAN: Yes you are right. I was aware of this possibility from the beginning of this project. My plan was to wait until it shows that the style will be used by many others - not just me ;) In this context, you are the first mentioning CTAN. I will use your impulse as an opportunity to inform myself about the necessary steps. If you already have some information or advice regarding the procedure, you are welcome to share this with me.

2. License: Again, yes you are right. I also noticed this some months ago. However, to avoid another unfortunate decision, I wanted to better inform myself and read more about feasible licenses. In the end, I do plan to re-license it, but it will probably take some time.

**Comment by vermiculus** [comment]
:smile: 

1. See [my question on TeX.SX](http://tex.stackexchange.com/q/161318/17423) regarding this point. I think anything you create that you want to share should go up. I mean, I doubt *anyone* is using `termmenu` right now, but it's up there. (It's in the wrong place right now, but it's up there...) Just [upload](http://ctan.org/upload) stuff. The `ctanify` tool is also pretty useful.
2. You should decide on a license before you upload to CTAN -- it will be simpler that way. The license also determines which distributions will pick it up.

**Comment by derric** [comment]
Almost done. I just re-licensed the cleanthesis style using the LPPL (see ef85979db40467d388cf2e974e806670273ad826).

Next step: Upload a CTAN package :)

**Comment by derric** [comment]
Also done! See http://ctan.org/pkg/cleanthesis
