### ISSUE TITLE
siunitx text does not fit in correctly

### ISSUE THREAD

**Issue by Tyde** [derric/cleanthesis#18]
When I write some units with the siunitx package, the text seems do be dirrerent to the other text. I've attached an image that shows this. I have the feeling, that siunitx takes a different typeface.
![weird text](https://cloud.githubusercontent.com/assets/1103207/8348402/549ea4d0-1b13-11e5-89bb-8378bdd370f2.png)

**Comment by Tyde** [comment]
I found a solution in the siunitx itself. One should use `\sisetup{detect-all}` to use the correct typeface

**Comment by derric** [comment]
Hey, did you try some of "the font detection options" of the siunitx package (see Font Detection in ftp://ftp.tex.ac.uk/pub/tex/macros/latex/exptl/siunitx/siunitx.pdf)?

- derric

**Comment by derric** [comment]
:smile:

It would be great if you could provide an updated screenshot and the usepackage statement for siunitx that works for you.

Thanks and all the best for your writing!

**Comment by Tyde** [comment]
Yep:
I used the following:

    \usepackage{siunitx}
    \sisetup{detect-all}
    [...]
    This is a siunitx test. This does not fit correctly here. \SI{300}{\kilogram} Feels weird in this text.


![unbenannt2](https://cloud.githubusercontent.com/assets/1103207/8348564/fd194736-1b14-11e5-818e-3cdc00ede097.png)

**Comment by derric** [comment]
Thank you again!
