### ISSUE TITLE
How can I get Umlauts to work?

### ISSUE THREAD

**Issue by tclass** [derric/cleanthesis#21]
Ä Ö Ü doesn't work

**Comment by johannesbottcher** [comment]
The example file uses `utf8` as default option for `inputenc`. Check which encoding your editor uses and change the option for `inputenc` or recode your files as utf8. [Wie überprüfe ich die Standardeingabekodierung meines Editors?](http://texwelt.de/wissen/fragen/2656/wie-uberprufe-ich-die-standardeingabekodierung-in-meinem-editor)

**Comment by derric** [comment]
You can also adjust setting in the thesis example file at line 85:
```
\usepackage[english]{babel}
```

And switch comments at line 119-122.
```
%\renewcaptionname{ngerman}{\figurename}{Abb.}
%\renewcaptionname{ngerman}{\tablename}{Tab.}
\renewcaptionname{english}{\figurename}{Fig.}
\renewcaptionname{english}{\tablename}{Tab.}
```

I hope this is kind of helpful for you.
Greetings, derric

**Comment by tclass** [comment]
yep, thx it worked :D
