### ISSUE TITLE
Itemize distance

### ISSUE THREAD

**Issue by HolgerVornholt** [derric/cleanthesis#26]
I'm using your style for my thesis and am struggling with the itemize environment. It has a quite unusual amount of space between two items. 

I tried to change this with 
\setlength{\itemsep}{VALUE}
\setlength{\parsep}{VALUE}

but did not succeed. Is the spacing intended? Do you have any hints on how I can change it?
Thanks,
Holger

EDIT: \setlength{\parskip}{WERT} worked. Only the question if it is inteded remains :).

**Comment by Riin** [comment]
I solved this problem with:
\setlist{noitemsep}

**Comment by bluscr33n** [comment]
For those who still struggle with this problem, have a look at the `enumitem` package: http://www.ctan.org/pkg/enumitem
It *pro­vides user con­trol over the lay­out of the three ba­sic list en­vi­ron­ments: enu­mer­ate, item­ize and de­scrip­tion.*

**Comment by derric** [comment]
@Riin @bluscr33n Thanks for your help!
