### ISSUE TITLE
Relicense Under Friendlier Terms

### ISSUE THREAD

**Issue by theonewolf** [derric/cleanthesis#28]
The GNU GPL is rather prohibitive in this case, requiring any derivative works to become open sourced if we use your style files.

For example, my thesis would need to become open source because I publish the PDF and I must host all the Latex source code somewhere etc.

See:

http://tex.stackexchange.com/questions/69007/the-gpl-and-latex-packages

Can you please re-license under a friendlier license?

Or allow people to ask you for a different license for special cases?

**Comment by theonewolf** [comment]
Also, a clear unambiguous clarification a la:

http://tex.stackexchange.com/questions/101439/what-license-for-releasing-latex-templates

Would also cover this issue.

**Comment by derric** [comment]
Done! I re-licensed the style using the LPPL (see ef85979db40467d388cf2e974e806670273ad826).

**Comment by theonewolf** [comment]
This might be moot based on all the Latex libraries I generally import, but this clause in the new license confuses me:

> 7. If you are not the Current Maintainer of the Work, you may 
> distribute a Compiled Work generated from a Derived Work, as long as 
> the Derived Work is distributed to all recipients of the Compiled 
> Work, and as long as the conditions of Clause 6, above, are met with 
> regard to the Derived Work.

Does derived work only mean the files of this project?  As in, only if we make edits to your source files do we need to disclose changes if we distributed a PDF?

**Comment by derric** [comment]
No - the produced PDF is not derived work: http://tex.stackexchange.com/questions/82713/is-a-pdf-output-from-a-latex-document-a-derived-work-from-the-lppl-standard-p

**Comment by johannesbottcher** [comment]
Hi there, [the whole thing confuses me](http://tex.stackexchange.com/questions/101439/what-license-for-releasing-latex-templates/273519#273519).
