### ISSUE TITLE
Possibility for different bibliography styles

### ISSUE THREAD

**Issue by Treggats** [derric/cleanthesis#30]
Hello,

would it be possible to use a different style for the bibliography? Or would I need to edit the sty file?

**Comment by Treggats** [comment]
After looking at the .sty file, I saw it was possible to have different types of bibstyles.
I have tried to edit the .sty file as can be seen in my commit https://github.com/Treggats/cleanthesis/commit/60dc0d02f4cf8e5b4eccebffac7d78c8d7e7975a
pdflatex seems to bork when I try to include apacite as package.
Am I on the right track here? This is my first time editing a .sty file, so I probably missed something.

**Comment by derric** [comment]
Hey,

Basically, you need to change the .sty file at line 284 from `style=\cthesis@bibstyle` to `style=apa` (as you proposed). In addition, you need to specify a language mapping, e.g., `\DeclareLanguageMapping{american}{american-apa}`. Please have a look at the [biblatex-apa](www.ctan.org/pkg/biblatex-apa package).

I hope this is kind of helpful for you.

**Comment by Treggats** [comment]
I made [two](https://github.com/derric/cleanthesis/commit/a715febc7aae617221854666d5edde29427233d8) [commits](https://github.com/derric/cleanthesis/commit/0419dad556e2c31d17911b693375fda9d60f4f64), adding APA support.

Seems to be working, although there are warnings about combining fancyhdr/titlesec with a koma script

    ./cleanthesis.sty: Class scrreprt Warning: Usage of package `fancyhdr' together(scrreprt)              with a KOMA-Script class is not recommended.
    ./cleanthesis.sty: Class scrreprt Warning: Usage of package `titlesec' together(scrreprt)              with a KOMA-Script class is not recommended.

**Comment by derric** [comment]
Okay. Great that it worked! Good luck for your document.

**Comment by retorquere** [comment]
APA doesn't seem to work anymore, I get a "style not supported" error. Authoryear is fairly close. Any changes of adding authoryear-ibid?
