### ISSUE TITLE
Wrong font in toc

### ISSUE THREAD

**Issue by magnucki** [derric/cleanthesis#33]
Using version 0.3.1 it seems like, the font of toc is different from the rest of the document

TOC Font
![screen shot 2015-10-01 at 15 34 10](https://cloud.githubusercontent.com/assets/3023216/10221996/f03943e2-6851-11e5-9956-c4720e31bab2.png)

Chapter Font
![screen shot 2015-10-01 at 15 34 18](https://cloud.githubusercontent.com/assets/3023216/10221997/f3bff6be-6851-11e5-8c84-845019a432e3.png)

I'm on pdfTeX 3.14159265-2.6-1.40.15 (TeX Live 2014) on OSX 10.10

**Comment by magnucki** [comment]
I added 2 lines to the `.sty` file. After `\RequirePackage{tocloft}` (Line 628)
```tex
\renewcommand{\cftchapfont}{\fontfamily{phv}\bfseries\selectfont}
\renewcommand{\cfttoctitlefont}{\thesischapterfont}
```
![screen shot 2015-10-01 at 16 06 17](https://cloud.githubusercontent.com/assets/3023216/10222848/70b192d2-6856-11e5-841d-f4f0cbc29537.png)

Still not sure, if this is the correct font for the chapter headings. Should be the right one though.

**Comment by derric** [comment]
Hey, Thanks! I fixed this issue based on your solution (e62216bb5962460359f4c9e45f13869b27d6315f).

![toc-fonts](https://cloud.githubusercontent.com/assets/839618/10413495/459bec30-6fab-11e5-8ade-d69df9d3a769.png)

**Comment by magnucki** [comment]
Thank you! Actually I just noticed, the List of Tables and List of Figures have the wrong font, too. 
fixed it with this two extra lines:
```tex
\renewcommand{\cftloftitlefont}{\thesischapterfont}
\renewcommand{\cftlottitlefont}{\thesischapterfont}
```

**Comment by derric** [comment]
Hey - great. I fixed the issue.
Thanks again!
