### ISSUE TITLE
Long chapter title cropped in footer

### ISSUE THREAD

**Issue by farbverlust** [derric/cleanthesis#34]
Hi derric,

thank you for the beautiful theme and your great work on ot.

I noticed that the title of chapters with a very long title is cropped in the footer of the document:
![image](https://cloud.githubusercontent.com/assets/8414709/10244686/456cd22a-6901-11e5-9218-13b51af7b60f.png)

I would like the title to simply wrap to the next line. I played around a long time with minipages and parboxes to achieve this, but did not manage to get them vertically aligned at the top.

Do you have a solution for this?

**Comment by derric** [comment]
Hey, I added a new package option called wrapfooter. You can activate it by using wrapfooter=true.
I hope this works for you.

![screenshot](https://cloud.githubusercontent.com/assets/839618/10270830/c30a07f8-6afe-11e5-850a-f70e5ab204de.png)

**Comment by farbverlust** [comment]
Thank you derric! This works great. You saved my PhD thesis from looking sloppy :-)
I will prepare a postcard once I handed it in next month!
