### ISSUE TITLE
Broken link to classic thesis style on the website

### ISSUE THREAD

**Issue by lorey** [derric/cleanthesis#45]
Hey Ricardo,

the link 'Classic Thesis Style' on the website is not working. The correct link is `http://www.miede.de/#classicthesis`. The old link was `http://www.miede.de/index.php?page=classicthesis` and returns a 404. I would have opened a PR but the site doesn't seem to be on GitHub so I'm leaving this here.

And also thanks for your work, of course! :+1:

**Comment by derric** [comment]
Should be fixed now. Thx
