### ISSUE TITLE
"Webseiten" instead of "Website" in bibliography  

### ISSUE THREAD

**Issue by EnricoMingo** [derric/cleanthesis#46]
I notice that all the @urls in the bib file are grouped all together in the bibliography under "Webseiten", should not be "Website" since everything is in English?

**Comment by johannesbottcher** [comment]
`\printbibliography[heading=subbibliography,title={Webseiten},type=online,prefixnumbers={@}]` 

The title is given with `title={Webseiten}`, you can replace *Webseiten* with *Wombat* if you are in the mood for it.

**Comment by derric** [comment]
@johannesbottcher: Thanks for your answer!
