### ISSUE TITLE
In Appendix, \chaptername not changed to Appendix

### ISSUE THREAD

**Issue by farbverlust** [derric/cleanthesis#47]
Hi, I am using the appendix package with cleanthesis. I noticed that inside the "appendices" environment, the chapter mark in the footer is still "Chapter A chaptername". I guess this holds for the standard \appendix command as well, but didn't test.

I fixed this by editing right below the lines
% **************************************************
% Header and Footer
% **************************************************

where I replaced \chaptername with \@chapapp. After this, the footer would read "Appendix A", but the chaptername was missing. I replaced \leftmark in the footer code below by \mbox{\leftmark} and everything works perfectly ("Appendix A chaptername").

Sorry for not filing a proper pull request, but I'm not fluent enough in Latex to judge if this is a proper fix or just a workaround.

Best, Ole

**Comment by johannesbottcher** [comment]
Using `\@chapapp` is the right command to use here and i think @derric will change it in the next release. 

For now, you can use `\renewcommand{\chaptername}{Wombat}` in your main file *after* `\appendix` (or after `\begin{appendices}`).

**Comment by derric** [comment]
@farbverlust Thanks for mentioning and fixing the issue!
I integrated your solution with commit c79b8b500a40c5bc99b56e35d2c42a39e2a933a9. However, I did not encountered the issue with a missing chapter name. Therefore I skipped the `\mbox{\leftmark}` part.

Thanks again!
