### ISSUE TITLE
List of figures does not show up in TOC

### ISSUE THREAD

**Issue by retorquere** [derric/cleanthesis#48]
I have bibliography=totoc and listof=totoc in the scrreprt options (just the default sample thesis-example.tex) but the bibliography and list of figures doesn't end up in the TOC.

**Comment by johannesbottcher** [comment]
`cleanthesis` loads the KOMA-incompatible package `tocloft` which officially destroys this KOMA-feature. You have to add the entries to the toc yourself. `\cleardoublepage\addcontentsline{toc}{chapter}{\listfigurename}` right before `listoffigures`.

**Comment by retorquere** [comment]
OK, got it.
