### ISSUE TITLE
Using bibtex file

### ISSUE THREAD

**Issue by matthieu-lapeyre** [derric/cleanthesis#5]
I do not really understand how I should include my bibtex file (generated with Mendeley). Usually I just add something like this at the end:

``` latex
\bibliographystyle{my_style}
\bibliography{my_bib_file}
```

But in the template, I saw a hardcoded bibtex file name in cleanthesis.sty `\bibliography{bib-refs}` so I do not really know how to proceed to include mine. It tried to replace it by my bibfile but it did not work.
It seems I am not enough expert Latex user to understand well ^^

Can you please explain me how I should proceed ?

Thanks

**Comment by olsgaard** [comment]
The documentation PDF only goes up to section 2.1.

To get this to work in the current version (as of writing) of cleanthesis, you need to find line 60 in `my-thesis-setup.tex`, which starts with `bibstyle=` and change it to `    bibstyle=authoryear,%`
