### ISSUE TITLE
Variable inter-paragraph spacing?

### ISSUE THREAD

**Issue by retorquere** [derric/cleanthesis#50]
Is there a way to prevent the variable inter-paragraph spacing? I'd rather have whitespace at the bottom of the page than have the paragraphs spaced differently on the separate pages.

**Comment by johannesbottcher** [comment]
`\raggedbottom`

**Comment by retorquere** [comment]
Super, thanks, that did work.

In the interim, I've also tried [this](http://tex.stackexchange.com/questions/152273/raggedbottom-before-headings) solution, and that gets me even prettier results; raggedbottom when the spacing would get too big, flushbottom otherwise.

**Comment by derric** [comment]
@johannesbottcher Thanks again ;)
