### ISSUE TITLE
Bibliography

### ISSUE THREAD

**Issue by RenanMP12** [derric/cleanthesis#51]
How do I set the bibliography to this template?

**Comment by johannesbottcher** [comment]
@RenanMP12  The example template already contains a bibliography.

**Comment by RenanMP12** [comment]
I know but it does not print out at the end and I do not know where I should substitute to mine and which sort of file should I use to set it. In other templates I used to use .bib

**Comment by johannesbottcher** [comment]
This template uses a bib file as well, please read the documentation. I don't consider this an issue in the sense of a github issue.

**Comment by derric** [comment]
Hey. I hope you successfully solved your bib problem. If not, please ask your question at our [Stack Exchange tag](http://tex.stackexchange.com/questions/tagged/cleanthesis). Thank you!
