### ISSUE TITLE
Section numbers broken with TeX Live 2015

### ISSUE THREAD

**Issue by fabianmeyer** [derric/cleanthesis#57]
I recently updated my system from Ubuntu 14.04 to Ubuntu 16.04, which includes the TeX Live 2015 distribution. After building my thesis, I recognized that the section numbers are broken (missing). To verify the bug, I checked out the clean thesis example from the git repository: same result.

![screenshot from 2016-05-19 09-08-41](https://cloud.githubusercontent.com/assets/6650294/15385504/57008710-1da2-11e6-9b94-e52513e819fe.png)

**Comment by johannesbottcher** [comment]
Get the current version of package `titlesec`, this is version `2.10.2`. You are most probably using `2.10.1`.

**Comment by fabianmeyer** [comment]
Thanks! That at least brought back the numbering, but the indentation is still broken:

![screenshot from 2016-05-19 10-02-03](https://cloud.githubusercontent.com/assets/6650294/15386592/eedece9c-1da8-11e6-8645-45168a1b0b4d.png)

**Comment by johannesbottcher** [comment]
Search for `titlesec` in your log-file. `cleanthesis` is *incompatible* with current versions of KOMA-script.

**Comment by johannesbottcher** [comment]
I just noticed that there is a `dev` branch available. The issue is fixed there.

**Comment by fabianmeyer** [comment]
Thanks for the hint, the changes from the dev branch fixed the issue!
