### ISSUE TITLE
Old font commands

### ISSUE THREAD

**Issue by johannesbottcher** [derric/cleanthesis#58]
KOMA dropped support of font commands, just like `memoir` did a while back. 

You have to explicitly activate them. 

```
\documentclass{scrreprt}
\usepackage{cleanthesis}
\begin{document}
\section{wombat}
\end{document}
```

**Comment by derric** [comment]
This is fixed in the develop branch.

**Comment by johannesbottcher** [comment]
Thanks for the recent updates, fixing stuff that is incompatible with KOMA-script. I appreciate it.

**Comment by derric** [comment]
You are welcome
