### ISSUE TITLE
Change chapters and sections to bold font

### ISSUE THREAD

**Issue by stefan-mueller** [derric/cleanthesis#62]
By default, the headings (captions, sections, subsections) are not in bold font. How can I change this? This is only a minor issue, but could improve readability of the text. 

Best,
Stefan

**Comment by johannesbottcher** [comment]
This is just what the layout is supposed to look like. The default is bold, but the template changes that for a better look. 

Using bold face, won't make any text more readable in most cases.

**Comment by derric** [comment]
Although I totally agree with @johannesbottcher, If you really want this, you can change it in the sty file in the lines 502 to 508.
