### ISSUE TITLE
Problem with Bibliography! 

### ISSUE THREAD

**Issue by arsalanshrn** [derric/cleanthesis#64]
Hi all,
I've just downloaded the clean thesis to use it for my master thesis. my problem is that \printbibliography does not work at all! Also the \cite does not work. my pdf does not have any bibliography. I'm not a profi in latex, any advice for me?
![problem](https://cloud.githubusercontent.com/assets/19910581/16010478/a27e63ae-3181-11e6-9495-0ab46bfdea48.png)

**Comment by johannesbottcher** [comment]
[Question mark instead of citation number](http://tex.stackexchange.com/q/63852)

[biblatex in a nutshell](http://tex.stackexchange.com/q/13509)

[Biblatex with Biber: Configuring my editor to avoid undefined citations](http://tex.stackexchange.com/questions/154751/)

**Comment by derric** [comment]
This is not a bug or error. Please check the links provided by @johannesbottcher.

**Comment by AlexAltea** [comment]
While I'm aware that this is not a bug/error, would it be possible to specify the build dependencies and appropriate configuration to compile CleanThesis' example? What steps would you follow to build CleanThesis from scratch on a new machine?

I'm facing the same issue and I've already wasted a couple of hours trying to solve it. At this point I would be happy even if someone just dropped an .OVF file with a pre-configured virtual machine. :-/

**Comment by Sapna714** [comment]
Hi, having exactly the same problem as described in this issue, any help please?
