### ISSUE TITLE
\subsubsection makes latex fail

### ISSUE THREAD

**Issue by masfaraud** [derric/cleanthesis#76]
Hi, 
I recently updated my linux distribution (Linux Mint 17.2->18). After update, I can't compile my latex document based on a cleanthesis template.
I discovered that the presence of `\subsubsection` makes it fail. Without, the compilation works.

The kind of error:
```
! Missing number, treated as zero.
<to be read again>
}
l.17 ...ion de la puissance d'un moteur thermique}
A number should have been here; I inserted `0'.
(If you can't figure out why I needed to see a number,
look up `weird error' in the index to The TeXbook.)
! Illegal unit of measure (pt inserted).
```

**Comment by derric** [comment]
Can you please try the develop branch.

**Comment by masfaraud** [comment]
It works with the dev branch!
Thank you!
