### ISSUE TITLE
sansserif option does not work in development branch

### ISSUE THREAD

**Issue by guillerodriguez** [derric/cleanthesis#77]
Hello,

I switched to the development branch to get the fix for #66 , but now the sansserif option does not work anymore. Is this expected?

Is it possible to use sansserif in the development branch, or to backport the fix for #66 to the main branch?

Guillermo

**Comment by derric** [comment]
Hi,
yes - this change was on purpose (see 5799c4fa182d586c05a06039c60c9af609615f77).
derric

**Comment by guillerodriguez** [comment]
I see. Was that because of some problems/issues with sans serif fonts, or just a matter of taste?
If the latter, then I guess that leaving the option there does not do any harm :)

**Comment by derric** [comment]
Kind of both. One reason was a series of font issues with the newer KOMA script. And personally I with a lot of people that long text documents should be printed with a serif font. And finally, I thought about different predefined font options for the theme, allowing users to some how choose other font types - however this is not implemented yet.

**Comment by guillerodriguez** [comment]
I see. I also like serif fonts better for long documents that are meant to be printed. But sans-serif is usually more comfortable for docs that are meant to be read online. And in any case I guess it is just a matter of preference.

I was initially attracted to cleanthesis by your statement that the design of the Clean Thesis style was inspired by user guide documents from Apple Inc. (e.g. iMovie '08 or Keynote '09). These all use sans-serif fonts.

Wouldn't it be a good idea to keep the sans-serif option for the time being (at least until it is replaced by the "several predefined font options" scheme that you mention in your comment) ? It does not do any harm for people that don't want to use it :)

**Comment by derric** [comment]
Okay, I added the sansserif option again. See 4f5e4e4aff19d2ca0c477883f658fa8e8245f93d.
Thanks for your activity!

**Comment by guillerodriguez** [comment]
You're welcome! Thank you for your great work.
