### ISSUE TITLE
Indent support - spanish user

### ISSUE THREAD

**Issue by jicaceres** [derric/cleanthesis#83]
[thesis-example.pdf](https://github.com/derric/cleanthesis/files/836305/thesis-example.pdf)
Hi!. I would love to use this beautiful thesis. But you know, in Spanish indents are mandatory.
I performed an online search and [found a workaround](http://tex.stackexchange.com/questions/233074/customizing-clean-thesis) It involves \makeatletter \makeaother usage (not so elegant) and it works but the resulting paragraph spacing is somehow distorted.
This is the code:
`\makeatletter
\pretocmd{\Hy@org@chapter}{\KOMAoptions{parskip=full}}{}{}
\pretocmd{\H@old@schapter}{\KOMAoptions{parskip=full}}{}{}
\pretocmd{\cleanchapterquote}{\KOMAoptions{parskip=full}}{}{}
\apptocmd{\Hy@org@chapter}{\KOMAoptions{parskip=false}}{}{}
\apptocmd{\H@old@schapter}{\KOMAoptions{parskip=false}}{}{}
\apptocmd{\cleanchapterquote}{\KOMAoptions{parskip=false}\vspace*{\baselineskip}}{}{}
\makeatother
`

The output is in the attached file and as you see, the indents are there but the paragraph spacing has been lost.
Then I used the package [indentfirst](http://texdoc.net/texmf-dist/doc/latex/tools/indentfirst.pdf) but it doesn't work at all with cleanthesis.
Would you be kind enough to provide a \parindent option for we spanish users?
Thanks in advance

**Comment by johannesbottcher** [comment]
`\setlength{\parindent}{1em}`

**Comment by guillerodriguez** [comment]
@jicaceres "But you know, in Spanish indents are mandatory". Mandatory? According to who?

**Comment by jicaceres** [comment]
[Real Academia Española - sangría](http://lema.rae.es/dpd/srv/search?id=PxrAnmVfND6FK0uGdT)
However, googling around I found that its use has been relaxed nowadays and it is acceptable exchange indent by blank line. Furthermore, both options should not been used together.

**Comment by jicaceres** [comment]
**johannesbottcher** suggestion worked like a charm. Many thanks to both of you!
