### ISSUE TITLE
pictures not showing up

### ISSUE THREAD

**Issue by Eroui** [derric/cleanthesis#87]
Hello, 

I've just started using this latex template for my master degree resume, and i wanted to add some figures and change the university picture by another one but the pictures doesn't show up.

I need some help. Is there a special method to add pictures and figures ?

Thank you.

**Comment by johannesbottcher** [comment]
Are pictures showing up using the unmodified template? Do you get any error messages?

**Comment by Eroui** [comment]
@johannesbottcher thank you for your answer, i just knew why there were no picture shown (i was getting no error), i used .jpg format instead of .png i still dont know why .jpg pictures does not work.

**Comment by johannesbottcher** [comment]
@Eroui Well, they should work as well.

**Comment by Eroui** [comment]
ow, no idea i've been trying to generate pictures as pdf (same as they did in the original template) but got no result

**Comment by derric** [comment]
Probably outdated :worried:
