### ISSUE TITLE
page numbers top right

### ISSUE THREAD

**Issue by godey4me** [derric/cleanthesis#96]
My university requires the page numbers to be top right of each page or centered at the bottom. Is it possible to change this in cleanthesis?

**Comment by johannesbottcher** [comment]
Yes, it is possible.
But changing the default layout, the reason to use the template.

**Comment by godey4me** [comment]
HOW?  If you can elaborate further. 
I checked the cleanthesis.sty before making my post and there is no obvious way to change it. I even checked stachexchage.com.

**Comment by johannesbottcher** [comment]
`\ohead{\pagemark}`  in the preamble with the development branch. 

But this changes the idea of the template, to have the layout. This template adapts spaghetti code from another template, with some add-ons. I would recommend to use a [different template](https://en.wikibooks.org/wiki/LaTeX/Scientific_Reports).

**Comment by godey4me** [comment]
Thanks.
