### ISSUE TITLE
subsubsection not working

### ISSUE THREAD

**Issue by stat1x** [derric/cleanthesis#97]
I cannot use subsubsection. It gives me an error like :  

`! Missing number, treated as zero.
<to be read again> 
                   }
l.33 \subsubsection{Subsubtitle}
`

**Comment by FlorentF9** [comment]
Same issue here!

**Comment by johannesbottcher** [comment]
Make an update of your TeX distribution.
Maybe using the dev branch will help as well.

**Comment by stat1x** [comment]
It works on the dev branch
