### ISSUE TITLE
Citation/referencing not working - even in example?

### ISSUE THREAD

**Issue by pr1nX** [derric/cleanthesis#99]
Hey Guys,

I'm trying to write my thesis with the cleanthesis template. But I have serious problems with the bibliography.

Even the example isn't working for me.

In chapter-introduction in row 22:
`\cite{Jurgens:2000,Jurgens:1995,Miede:2011,Kohm:2011,Apple:keynote:2010,Apple:numbers:2010,Apple:pages:2010}`

produces the following output in the corresponding PDF file:

### [Jurgens:2000; Jurgens:1995; Miede:2011; Kohm:2011; Apple:keynote:2010; Apple:numbers:2010; Apple:pages:2010]

Does anyone have a clue? Maybe there is something wrong with my setup.

**Comment by johannesbottcher** [comment]
Have a look at vhttps://
en.m.wikibooks.org/wiki/LaTeX/Bibliographies_with_biblatex_and_biber

You need to use an extra tool.

**Comment by pr1nX** [comment]
Wow that's it. It works! :)

Thank you so much!
